CREATE TABLE choretastic_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    nickname TEXT,
    points INTEGER DEFAULT 0 NOT NULL,
    home_id INTEGER
        REFERENCES choretastic_homes(id) ON DELETE SET NULL,
    date_created TIMESTAMP NOT NULL DEFAULT now()
);