CREATE TYPE STATUS AS ENUM('pending', 'complete');

CREATE TABLE choretastic_tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    task_name TEXT NOT NULL,
    points INTEGER NOT NULL DEFAULT 0,
    status STATUS NOT NULL DEFAULT 'pending',
    date_created TIMESTAMP NOT NULL DEFAULT now(),
    date_completed TIMESTAMP,
    assignee_id INTEGER NOT NULL
        REFERENCES choretastic_users(id) ON DELETE SET NULL,
    home_id INTEGER NOT NULL
        REFERENCES choretastic_homes(id) ON DELETE SET NULL
);